### PR TITLE
Basic Chrome port of the Firefox add-on

### PR DESCRIPTION
**Pull request by ckarlof**
@vladikoff, @nchapman r?

This is a PR into my fork of mozilla/chronicle-addon.

### CODE REVIEW

**Comment by ckarlof** [comment]
Instructions:

1) Fork, and "load unpacked extension" in Chrome extension dev page.
2) Log into Chronicle Dev server (Chrome doesn't have prefs, so you need to edit the code directly to change the URL, currently).
3) Visit away.

**Comment by vladikoff** [comment]
Works!

**Comment by ckarlof** [comment]
Merging.

**Comment by ckarlof** [comment]
It's been a while since I've distributed Chrome extensions, but I think they generally have to be distributed through the Chrome Store (https://developer.chrome.com/extensions/hosting). Not big deal -- just need a Google dev account. There are some exceptions listed on that page, but I think the Chrome store would be the most straightforward. You can also make your extension unpublished and only available to trusted testers as well.

/cc @6a68, @nchapman

**Comment by vladikoff** [comment]
Should this be PR'd against https://github.com/mozilla/chronicle-addon?

**Comment by nchapman** [comment]
> You can also make your extension unpublished and only available to trusted testers as well.

@ckarlof Yeah this sounds like a great idea. We'll look into doing this.

> Should this be PR'd against https://github.com/mozilla/chronicle-addon?

@vladikoff We're going to keep this as an unsupported platform for a little while.

**Comment by nchapman** [comment]
I ran into a couple of issues:

Not all pages are making it into Chronicle. It seems that because `onVisited` is [fired before the page loads](https://developer.chrome.com/extensions/history#event-onVisited), there isn't always a title which makes the server unhappy:

```
{"statusCode":400,"error":"Bad Request","message":"title is not allowed to be empty","validation":{"source":"payload","keys":["title"]}}
```

Also, the toolbar button doesn't do anything yet. Can it navigate to `SERVER_URL`?

**Pull request merged**
